### ISSUE TITLE
Updates on the 152 packages with if-cond bug (March 2017)?

### ISSUE THREAD

**Issue by HenrikBengtsson** [kalibera/rifcond#1]
I saw your `env _R_CHECK_LENGTH_1_CONDITION_=true R CMD check` reports on [152 packages with the if-cond bug](https://github.com/kalibera/rifcond/tree/master/outputs).  Thxs.

Q. Was this an extensive search/test on _all_ CRAN and Bioconductor packages at the time?

Q. Did you reach out to the authors, i.e. are they even aware?  (I've reached out to 10-20 of them as I've discovered this independently - some have fixed it).

I'd like to propose to make `_R_CHECK_LENGTH_1_CONDITION_=true` the default behavior for R 3.5.0, but maybe the number of buggy packages needs to be pushed down a bit more before that happens.

**Comment by kalibera** [comment]
Yes, that experiment was run an all CRAN+BIOC packages at that time (well, all that I could run). We will have to run again and get back to maintainers who did not fix. And yes, indeed, the plan is to turn this to an error by default as soon as packages get fixed.

**Comment by HenrikBengtsson** [comment]
thxs - that's good news.
